# Site settings
title: USTC C Programming Language I
description: Main page for USTC C Programming Language I
#baseurl: "https://localhost:4000" # the subpath of your site, e.g. /blog
url: "https://cs011164.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Si-Yuan Zhuang
user_description: USTC
email: zsy9509[AT]mail.ustc.edu.cn
#twitter_username: suquark
github_username:  suquark
#gplus_username:  lorem_ipsum
disqus_username: suquark

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
